import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import Header from './components/Header/Header'

const OpenSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Armageddon 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        <Header/>
        {children}
        <img src="./planeta.jpg" alt="back"  className='back'/>
      </body>
    </html>
  )
}

